use_frameworks!

platform :ios, '13.0'

# hier wird man wahrscheinlich weitere pods (firebase?) integrieren koennen
# nehmen wir mal einen einfachen....

pod 'Toast-Swift', '~> 5.0.0'

target 'TKExtentionsToolKit_Example' do
  pod 'TKExtentionsToolKit', :path => '../'

  target 'TKExtentionsToolKit_Tests' do
    inherit! :search_paths

    
  end
end
