use_frameworks!

platform :ios, '9.0'

target 'TKExtentionsToolKit_Example' do
  pod 'TKExtentionsToolKit', :path => '../'

  target 'TKExtentionsToolKit_Tests' do
    inherit! :search_paths

    
  end
end
